<?php
echo "<form action=\"".DIRURL."/registro\" method=\"POST\">";
echo "<br>";
echo "<label for=\"email\">Email: <input type=\"text\" name=\"email\" ></label>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<label for=\"contraseña\">Contraseña: <input type=\"text\" name=\"pass1\" ></label>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<label for=\"contraseña\">Contraseña: <input type=\"text\" name=\"pass2\" ></label>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<br>";
echo "<input type=\"submit\" name= \"enviar\" value=\"Enviar\">";
echo "<br>";
echo "</form>";
echo "<br>";